// Generated from data/apps.yaml and data/en.yaml. Do not edit this file directly.
export const siteData = {
  "organization": {
    "name": "Horama Apps",
    "description": "Horama Apps es una incubadora y semillero de aplicaciones independientes. Creamos productos útiles, los llevamos a una primera comunidad y buscamos patrocinio, partnerships o funding para darles infraestructura y continuidad.",
    "github": "https://github.com/horama-apps",
    "partnerships": [
      "Patrocinio",
      "Infraestructura",
      "Distribución",
      "Funding",
      "Colaboración técnica"
    ]
  },
  "apps": [
    {
      "slug": "framewise",
      "name": "Framewise",
      "monogram": "FW",
      "logo": "/apps/framewise/logo.svg",
      "theme": "dark",
      "tagline": "Tu archivo. Tu criterio. Ahora también en iPhone.",
      "summary": "Framewise analiza, califica y organiza sesiones fotográficas desde el escritorio o su app companion para iPhone, conectada a tu servicio local. Horama no recibe, almacena ni entrena con tus fotografías.",
      "pitch": "Tu archivo fotográfico no debería pagar con privacidad la comodidad de una herramienta inteligente. Framewise encuentra las tomas más fuertes, explica por qué funcionan y ayuda a mejorar únicamente lo necesario. En iPhone puedes elegir fotos de tu biblioteca, enviarlas a tu propio servicio de análisis y revisar resultados y versiones editadas desde una experiencia móvil privada. Los originales permanecen intactos y tus decisiones siguen siendo tuyas.",
      "opportunity_title": "Criterio editorial, también desde tu iPhone.",
      "opportunity_body": "Trabaja sesiones completas en tu computadora o selecciona fotos desde la biblioteca del iPhone. Framewise conecta ambos flujos con análisis explicable, una cola privada y ediciones que respetan al sujeto, la composición y la intención.",
      "opportunity_highlights": [
        "App companion para iPhone",
        "Originales intactos",
        "Procesamiento bajo tu control"
      ],
      "audience": [
        "Fotógrafos",
        "Creadores móviles",
        "Estudios creativos"
      ],
      "features": [
        "Escritorio e iPhone: analiza carpetas completas o elige fotos directamente desde tu biblioteca de iOS",
        "Selección explicable: crítica, puntuación, duplicados y decisiones editoriales en una biblioteca privada por dispositivo",
        "Flujo completo: cola de análisis, edición fiel, versiones locales y captions para compartir sin tocar el original"
      ],
      "version": "1.0.0",
      "status": "stable",
      "status_label": "Desktop v1 · iPhone companion",
      "color": "#d8ff4f",
      "ink": "#0b0d0b",
      "accent": "#ff8a4b",
      "demo": "/apps/framewise/framewise-demo.gif",
      "demo_label": "DEMO / FLUJO REAL",
      "demo_title": "Una sesión completa en escritorio, conectada con iPhone.",
      "demo_caption": "Recorrido real por Framewise: contact sheet, análisis explicable y biblioteca de versiones editadas. La app companion lleva la selección, el seguimiento y los resultados a iPhone mientras el servicio de análisis sigue bajo tu control.",
      "demo_alt": "Demostración de Framewise analizando una sesión fotográfica conectada con su app para iPhone",
      "support_ask": "Buscamos fotógrafos, creadores móviles y estudios que prueben el flujo entre escritorio e iPhone, además de aliados de distribución y hardware local.",
      "roadmap": [
        {
          "title": "Privacidad por arquitectura",
          "description": "Fotografías, análisis y decisiones permanecen en el equipo del usuario",
          "state": "done"
        },
        {
          "title": "Selección profesional explicable",
          "description": "Crítica, ranking, duplicados, comparación, decisiones, XMP y limpieza recuperable",
          "state": "done"
        },
        {
          "title": "Companion para iPhone",
          "description": "Selección con PhotoKit, bibliotecas privadas, cola de análisis, ediciones y captions desde iOS",
          "state": "done"
        }
      ]
    },
    {
      "slug": "horama-3d",
      "name": "Horama 3D",
      "monogram": "H3",
      "logo": "/apps/horama-3d/mark.png",
      "tagline": "Configura, visualiza y fabrica en un solo lugar.",
      "summary": "Un configurador web que transforma modelos e imágenes en piezas 3D imprimibles, directamente en el navegador y sin servicios externos.",
      "pitch": "Horama 3D acerca la personalización paramétrica a cualquier navegador. Reúne visor, validación STL, geometría local y exportación en una sola experiencia. Sus módulos convierten modelos, imágenes y texto en productos listos para fabricar sin enviar los archivos del usuario a otro servicio.",
      "audience": [
        "Makers",
        "Fabricación digital",
        "E-commerce"
      ],
      "features": [
        "Procesamiento local: visor, validación STL y generación de geometría en el navegador",
        "Módulos listos: lámparas, urnas, clickers, texturas, letreros y brazaletes",
        "Imagen por capas: cuantización por color y exportación multicolor en 3MF"
      ],
      "version": "1.0.0",
      "status": "stable",
      "status_label": "v1.0 pública",
      "color": "#ffc400",
      "ink": "#111111",
      "accent": "#fff3b0",
      "product_url": "https://horama-apps.github.io/Horama3D/?demo=true",
      "product_cta_label": "Ver Configurador ↓",
      "embed_url": "https://horama-apps.github.io/Horama3D/?demo=true",
      "embed_label": "CONFIGURADOR INTERACTIVO",
      "embed_title": "Diseña una pieza desde cero.",
      "embed_caption": "Prueba el generador de letreros directamente aquí. Esta demostración permite configurar y visualizar el modelo, pero mantiene la descarga deshabilitada.",
      "support_ask": "Buscamos comercios piloto, soporte de infraestructura y expertos en 3D web.",
      "roadmap": [
        {
          "title": "Motor 3D local",
          "description": "Carga, validación, órbita, autoencuadre y operaciones geométricas en el navegador",
          "state": "done"
        },
        {
          "title": "Catálogo modular",
          "description": "Lámparas, urnas con cavidad y ribs, clickers, texturas, letreros y brazaletes",
          "state": "done"
        },
        {
          "title": "Image Layers multicolor",
          "description": "Imagen cuantizada convertida en capas de color y empaquetada como 3MF",
          "state": "done"
        },
        {
          "title": "Llaveros desde imagen",
          "description": "Nuevo módulo de imagen a geometría con controles de fabricación",
          "state": "current"
        },
        {
          "title": "Configurador comercial",
          "description": "Catálogo, cotización y checkout",
          "state": "next"
        }
      ]
    },
    {
      "slug": "genai-studio",
      "name": "GenAI Studio",
      "monogram": "G",
      "logo": "/apps/genai-studio/logo.png",
      "theme": "dark",
      "tagline": "Tu estudio de contenido con IA, en cualquier pantalla.",
      "summary": "Una interfaz simple y responsiva para convertir workflows de IA en herramientas de producción accesibles desde iPhone, Android o computadora.",
      "pitch": "GenAI Studio convierte una instalación propia de ComfyUI en un estudio de producción usable por todo el equipo. Negocios, influencers y creadores pueden editar imágenes, transformar estilos, generar audio y descargar resultados sin navegar grafos técnicos. Cada workflow nuevo aparece como una herramienta clara y reutilizable, lista para trabajar desde el teléfono o la computadora.",
      "opportunity_title": "Menos nodos. Más contenido listo para publicar.",
      "opportunity_body": "Lleva tus workflows de IA a una interfaz que entiende el equipo creativo. Elige una modalidad, carga referencias, escribe la instrucción y sigue el resultado desde una cola unificada, usando tu propia infraestructura.",
      "opportunity_highlights": [
        "Diseñado para móvil",
        "Workflows reutilizables",
        "Infraestructura propia"
      ],
      "audience": [
        "Negocios y marcas",
        "Influencers",
        "Creadores de contenido"
      ],
      "features": [
        "Producción multiformato: edición y simplificación de imágenes, generación de voz y espacio preparado para video",
        "Experiencia sin complejidad técnica: formularios claros, uploads, micrófono, cola de trabajos y descarga de resultados",
        "Catálogo extensible: agrega nuevos workflows de ComfyUI sin reescribir la interfaz ni el backend"
      ],
      "version": "0.1.0",
      "status": "alpha",
      "status_label": "Alpha funcional",
      "color": "#ff6a3d",
      "ink": "#101114",
      "accent": "#ffd8cc",
      "support_ask": "Buscamos negocios, influencers y equipos de contenido para diseñar workflows repetibles, además de aliados con infraestructura de GPU y distribución creativa.",
      "roadmap": [
        {
          "title": "Estudio responsivo",
          "description": "Interfaz para iPhone, Android y computadora con jobs asíncronos y resultados descargables",
          "state": "done"
        },
        {
          "title": "Imagen y voz",
          "description": "Edición visual, simplificación de estilo y voz desde texto con audio de referencia",
          "state": "done"
        },
        {
          "title": "Flujos para contenido",
          "description": "Presets para campañas, producto, redes sociales y producción de video",
          "state": "current"
        },
        {
          "title": "Espacios de equipo",
          "description": "Biblioteca compartida, permisos e historial por marca o creador",
          "state": "next"
        }
      ]
    },
    {
      "slug": "kiroku",
      "name": "Kiroku",
      "monogram": "K",
      "logo": "/apps/kiroku/logo.svg",
      "theme": "dark",
      "tagline": "Tu memoria privada, lista para volver a ella.",
      "summary": "Un sistema de memoria personal para iPhone y Apple Watch que convierte voz, audio y video compartido en notas, tareas, respuestas y mapas conceptuales privados.",
      "pitch": "Las ideas, acuerdos y recuerdos importantes suelen aparecer cuando no hay tiempo para escribir. Kiroku los captura desde el iPhone, Apple Watch, widgets o la hoja de compartir y los convierte en memoria estructurada. Ask Kiroku responde con fuentes navegables, las tareas conservan su vínculo con la nota original y los mapas conceptuales revelan relaciones entre personas, proyectos, lugares, temas y decisiones. SwiftData mantiene al iPhone como fuente de verdad, mientras PostgreSQL, pgvector, Whisper y Ollama operan detrás de una API privada.",
      "opportunity_title": "Captura una vez. Recuerda, conecta y actúa después.",
      "opportunity_body": "Cada memoria puede convertirse en una nota consultable, una tarea con fecha y prioridad, una fuente para una respuesta privada o un nodo dentro de un mapa conceptual. Los grupos permiten compartir únicamente las notas elegidas sin ceder la propiedad ni abrir toda la biblioteca personal.",
      "opportunity_highlights": [
        "Captura en iPhone, Apple Watch y Share Sheet",
        "Ask Kiroku y mapas conceptuales con fuentes",
        "Grupos privados con control por nota"
      ],
      "audience": [
        "Personas con muchas ideas",
        "Profesionales y reuniones",
        "Familias y grupos privados"
      ],
      "features": [
        "Captura donde ocurre la idea: grabación en iPhone y Apple Watch, widgets, Control Center y Share Extension para audio o video",
        "Memoria que trabaja contigo: notas estructuradas, tareas editables, Ask Kiroku con búsqueda híbrida y mapas conceptuales navegables",
        "Privacidad con colaboración explícita: SwiftData local, API autenticada, sesiones en Keychain y grupos que comparten sólo cada nota elegida"
      ],
      "version": "0.8.0",
      "status": "alpha",
      "status_label": "Alpha privada · iPhone + Watch",
      "color": "#0171c6",
      "ink": "#0b0d10",
      "accent": "#9fd5ff",
      "support_ask": "Buscamos usuarios de iPhone y Apple Watch que quieran probar captura cotidiana, tareas, Ask Kiroku, mapas conceptuales, widgets y grupos privados antes de ampliar la sincronización y el recuerdo proactivo.",
      "roadmap": [
        {
          "title": "Captura y memoria persistente",
          "description": "SwiftUI, SwiftData, grabación nativa, Share Extension y jobs privados con Whisper y Ollama",
          "state": "done"
        },
        {
          "title": "Inteligencia con fuentes",
          "description": "Tareas estructuradas, Ask Kiroku con búsqueda híbrida y mapas conceptuales enlazados a cada nota",
          "state": "done"
        },
        {
          "title": "Kiroku alrededor de ti",
          "description": "Apple Watch, widgets, Control Center, Action button, autenticación con Google y grupos privados",
          "state": "done"
        },
        {
          "title": "Memoria multidispositivo",
          "description": "Sincronización autenticada, recordatorios, tareas recurrentes, calendario y recuperación contextual",
          "state": "current"
        },
        {
          "title": "Recuerdo físico y proactivo",
          "description": "Seeed Studio ReSpeaker, Seeed Studio Thermal Sticky y resúmenes configurables con controles explícitos de privacidad",
          "state": "next"
        }
      ]
    }
  ]
} as const;
export const siteTranslations = {
  "organization": {
    "description": "Horama Apps is an incubator and seedbed for independent applications. We build useful products, bring them to their first community, and seek sponsorships, partnerships, or funding to give them infrastructure and continuity.",
    "partnerships": [
      "Sponsorship",
      "Infrastructure",
      "Distribution",
      "Funding",
      "Technical collaboration"
    ]
  },
  "apps": {
    "framewise": {
      "tagline": "Your archive. Your judgment. Now on iPhone too.",
      "summary": "Framewise analyzes, scores, and organizes photo shoots from the desktop or its iPhone companion app connected to your local service. Horama never receives, stores, or trains on your photographs.",
      "pitch": "Your photo archive should not have to trade privacy for intelligent tools. Framewise finds the strongest frames, explains why they work, and helps improve only what needs attention. On iPhone, you can choose photos from your library, send them to your own analysis service, and review results and edited versions in a private mobile experience. Originals remain untouched, and your decisions remain yours.",
      "opportunity_title": "Editorial judgment, now on your iPhone too.",
      "opportunity_body": "Work through full shoots on your computer or select photos from your iPhone library. Framewise connects both workflows with explainable analysis, a private queue, and edits that respect subject, composition, and intent.",
      "opportunity_highlights": [
        "iPhone companion app",
        "Originals stay untouched",
        "Processing under your control"
      ],
      "audience": [
        "Photographers",
        "Mobile creators",
        "Creative studios"
      ],
      "features": [
        "Desktop and iPhone: analyze complete folders or choose photos directly from your iOS library",
        "Explainable culling: critique, scoring, duplicates, and editorial decisions in a private per-device library",
        "Complete workflow: analysis queue, faithful editing, local versions, and captions for sharing without touching the original"
      ],
      "demo_label": "DEMO / REAL WORKFLOW",
      "demo_title": "A complete desktop shoot, connected to iPhone.",
      "demo_caption": "A real Framewise walkthrough: contact sheet, explainable analysis, and an edited-version library. The companion app brings selection, progress, and results to iPhone while the analysis service remains under your control.",
      "demo_alt": "Framewise demo analyzing a photo shoot connected to its iPhone app",
      "status_label": "Desktop v1 · iPhone companion",
      "support_ask": "We are looking for photographers, mobile creators, and studios to test the desktop-to-iPhone workflow, plus distribution and local-hardware partners.",
      "roadmap": [
        {
          "title": "Privacy by architecture",
          "description": "Photos, analyses, and decisions stay on the user's computer",
          "state": "done"
        },
        {
          "title": "Explainable professional culling",
          "description": "Critique, ranking, duplicates, comparison, decisions, XMP, and recoverable cleanup",
          "state": "done"
        },
        {
          "title": "iPhone companion",
          "description": "PhotoKit selection, private libraries, analysis queue, edits, and captions from iOS",
          "state": "done"
        }
      ]
    },
    "horama-3d": {
      "tagline": "Configure, visualize, and manufacture in one place.",
      "summary": "A web configurator that turns models and images into printable 3D parts, directly in the browser and without external services.",
      "pitch": "Horama 3D brings parametric customization to any browser. It combines a viewer, STL validation, local geometry, and export in one experience. Its modules turn models, images, and text into manufacturing-ready products without sending the user's files to another service.",
      "audience": [
        "Makers",
        "Digital manufacturing",
        "E-commerce"
      ],
      "features": [
        "Local processing: viewer, STL validation, and in-browser geometry generation",
        "Ready modules: lamps, urns, clickers, textures, signs, and bracelets",
        "Image Layers: color quantization and multicolor 3MF export"
      ],
      "product_cta_label": "View Configurator ↓",
      "embed_label": "INTERACTIVE CONFIGURATOR",
      "embed_title": "Design a piece from scratch.",
      "embed_caption": "Try the sign generator directly here. This demo lets you configure and preview the model while keeping downloads disabled.",
      "status_label": "Public v1.0",
      "support_ask": "We are looking for pilot shops, infrastructure support, and web 3D experts.",
      "roadmap": [
        {
          "title": "Local 3D engine",
          "description": "In-browser loading, validation, orbiting, auto-framing, and geometry operations",
          "state": "done"
        },
        {
          "title": "Modular catalog",
          "description": "Lamps, cavity-and-rib urns, clickers, textures, signs, and bracelets",
          "state": "done"
        },
        {
          "title": "Multicolor Image Layers",
          "description": "A quantized image converted into color layers and packaged as 3MF",
          "state": "done"
        },
        {
          "title": "Image keychains",
          "description": "A new image-to-geometry module with manufacturing controls",
          "state": "current"
        },
        {
          "title": "Commercial configurator",
          "description": "Catalog, quoting, and checkout",
          "state": "next"
        }
      ]
    },
    "genai-studio": {
      "tagline": "Your AI content studio, on any screen.",
      "summary": "A simple responsive interface that turns AI workflows into production tools available from iPhone, Android, or desktop.",
      "pitch": "GenAI Studio turns a self-hosted ComfyUI installation into a production studio the whole team can use. Businesses, influencers, and creators can edit images, transform styles, generate audio, and download results without navigating technical graphs. Every new workflow becomes a clear, reusable tool ready to use from a phone or computer.",
      "opportunity_title": "Fewer nodes. More content ready to publish.",
      "opportunity_body": "Bring your AI workflows into an interface your creative team understands. Choose a format, upload references, write the instruction, and follow the result in one queue using your own infrastructure.",
      "opportunity_highlights": [
        "Mobile-first design",
        "Reusable workflows",
        "Your own infrastructure"
      ],
      "audience": [
        "Businesses and brands",
        "Influencers",
        "Content creators"
      ],
      "features": [
        "Multi-format production: image editing and simplification, voice generation, and a space ready for video",
        "No technical complexity: clear forms, uploads, microphone recording, job queue, and result downloads",
        "Extensible catalog: add new ComfyUI workflows without rewriting the interface or backend"
      ],
      "status_label": "Functional alpha",
      "support_ask": "We are looking for businesses, influencers, and content teams to design repeatable workflows, plus partners in GPU infrastructure and creative distribution.",
      "roadmap": [
        {
          "title": "Responsive studio",
          "description": "iPhone, Android, and desktop interface with asynchronous jobs and downloadable results",
          "state": "done"
        },
        {
          "title": "Image and voice",
          "description": "Visual editing, style simplification, and text-to-voice with reference audio",
          "state": "done"
        },
        {
          "title": "Content workflows",
          "description": "Presets for campaigns, products, social media, and video production",
          "state": "current"
        },
        {
          "title": "Team spaces",
          "description": "Shared library, permissions, and history for each brand or creator",
          "state": "next"
        }
      ]
    },
    "kiroku": {
      "tagline": "Your private memory, ready when you return.",
      "summary": "A personal-memory system for iPhone and Apple Watch that turns voice, shared audio, and video into private notes, tasks, answers, and concept maps.",
      "pitch": "Important ideas, agreements, and memories often appear when there is no time to write. Kiroku captures them from iPhone, Apple Watch, widgets, or the Share Sheet and turns them into structured memory. Ask Kiroku answers with navigable sources, tasks retain their link to the original note, and concept maps reveal relationships among people, projects, places, themes, and decisions. SwiftData keeps iPhone as the source of truth while PostgreSQL, pgvector, Whisper, and Ollama operate behind a private API.",
      "opportunity_title": "Capture once. Remember, connect, and act later.",
      "opportunity_body": "Every memory can become a searchable note, a task with a due date and priority, a source for a private answer, or a node in a concept map. Groups share only the notes you choose without transferring ownership or opening your full library.",
      "opportunity_highlights": [
        "Capture on iPhone, Apple Watch, and Share Sheet",
        "Ask Kiroku and sourced concept maps",
        "Private groups with note-level control"
      ],
      "audience": [
        "People with many ideas",
        "Professionals and meetings",
        "Families and private groups"
      ],
      "features": [
        "Capture where ideas happen: recording on iPhone and Apple Watch, widgets, Control Center, and a Share Extension for audio or video",
        "Memory that works with you: structured notes, editable tasks, hybrid Ask Kiroku retrieval, and navigable concept maps",
        "Privacy with explicit collaboration: local SwiftData, an authenticated API, Keychain sessions, and groups that share only each selected note"
      ],
      "status_label": "Private alpha · iPhone + Watch",
      "support_ask": "We are looking for iPhone and Apple Watch users to test everyday capture, tasks, Ask Kiroku, concept maps, widgets, and private groups before expanding synchronization and proactive recall.",
      "roadmap": [
        {
          "title": "Capture and persistent memory",
          "description": "SwiftUI, SwiftData, native recording, Share Extension, and private Whisper/Ollama jobs",
          "state": "done"
        },
        {
          "title": "Intelligence with sources",
          "description": "Structured tasks, hybrid Ask Kiroku retrieval, and concept maps linked to every source note",
          "state": "done"
        },
        {
          "title": "Kiroku around you",
          "description": "Apple Watch, widgets, Control Center, Action button, Google authentication, and private groups",
          "state": "done"
        },
        {
          "title": "Multi-device memory",
          "description": "Authenticated sync, reminders, recurring tasks, calendar integration, and contextual recall",
          "state": "current"
        },
        {
          "title": "Physical and proactive recall",
          "description": "Seeed Studio ReSpeaker, Seeed Studio Thermal Sticky, and configurable digests with explicit privacy controls",
          "state": "next"
        }
      ]
    }
  }
} as const;
