// Generated from data/apps.yaml and data/en.yaml. Do not edit this file directly.
export const siteData = {
  "organization": {
    "name": "Horama Apps",
    "description": "Horama Apps es una incubadora y semillero de aplicaciones independientes. Creamos productos útiles, los llevamos a una primera comunidad y buscamos patrocinio, partnerships o funding para darles infraestructura y continuidad.",
    "github": "https://github.com/horama-apps",
    "partnerships": [
      "Patrocinio",
      "Infraestructura",
      "Distribución",
      "Funding",
      "Colaboración técnica"
    ]
  },
  "apps": [
    {
      "slug": "framewise",
      "name": "Framewise",
      "monogram": "FW",
      "logo": "/apps/framewise/logo.svg",
      "theme": "dark",
      "tagline": "Tu archivo. Tu criterio. Ahora también en iPhone.",
      "summary": "Framewise analiza, califica y organiza sesiones fotográficas desde el escritorio o su app companion para iPhone, conectada a tu servicio local. Horama no recibe, almacena ni entrena con tus fotografías.",
      "pitch": "Tu archivo fotográfico no debería pagar con privacidad la comodidad de una herramienta inteligente. Framewise encuentra las tomas más fuertes, explica por qué funcionan y ayuda a mejorar únicamente lo necesario. En iPhone puedes elegir fotos de tu biblioteca, enviarlas a tu propio servicio de análisis y revisar resultados y versiones editadas desde una experiencia móvil privada. Los originales permanecen intactos y tus decisiones siguen siendo tuyas.",
      "opportunity_title": "Criterio editorial, también desde tu iPhone.",
      "opportunity_body": "Trabaja sesiones completas en tu computadora o selecciona fotos desde la biblioteca del iPhone. Framewise conecta ambos flujos con análisis explicable, una cola privada y ediciones que respetan al sujeto, la composición y la intención.",
      "opportunity_highlights": [
        "App companion para iPhone",
        "Originales intactos",
        "Procesamiento bajo tu control"
      ],
      "audience": [
        "Fotógrafos",
        "Creadores móviles",
        "Estudios creativos"
      ],
      "features": [
        "Escritorio e iPhone: analiza carpetas completas o elige fotos directamente desde tu biblioteca de iOS",
        "Selección explicable: crítica, puntuación, duplicados y decisiones editoriales en una biblioteca privada por dispositivo",
        "Flujo completo: cola de análisis, edición fiel, versiones locales y captions para compartir sin tocar el original"
      ],
      "version": "1.0.0",
      "status": "stable",
      "status_label": "Desktop v1 · iPhone companion",
      "color": "#d8ff4f",
      "ink": "#0b0d0b",
      "accent": "#ff8a4b",
      "demo": "/apps/framewise/framewise-demo.gif",
      "demo_label": "DEMO / FLUJO REAL",
      "demo_title": "Una sesión completa en escritorio, conectada con iPhone.",
      "demo_caption": "Recorrido real por Framewise: contact sheet, análisis explicable y biblioteca de versiones editadas. La app companion lleva la selección, el seguimiento y los resultados a iPhone mientras el servicio de análisis sigue bajo tu control.",
      "demo_alt": "Demostración de Framewise analizando una sesión fotográfica conectada con su app para iPhone",
      "support_ask": "Buscamos fotógrafos, creadores móviles y estudios que prueben el flujo entre escritorio e iPhone, además de aliados de distribución y hardware local.",
      "roadmap": [
        {
          "title": "Privacidad por arquitectura",
          "description": "Fotografías, análisis y decisiones permanecen en el equipo del usuario",
          "state": "done"
        },
        {
          "title": "Selección profesional explicable",
          "description": "Crítica, ranking, duplicados, comparación, decisiones, XMP y limpieza recuperable",
          "state": "done"
        },
        {
          "title": "Companion para iPhone",
          "description": "Selección con PhotoKit, bibliotecas privadas, cola de análisis, ediciones y captions desde iOS",
          "state": "done"
        }
      ]
    },
    {
      "slug": "horama-3d",
      "name": "Horama 3D",
      "monogram": "H3",
      "logo": "/apps/horama-3d/mark.png",
      "tagline": "Configura, visualiza y fabrica en un solo lugar.",
      "summary": "Un configurador web que transforma modelos e imágenes en piezas 3D imprimibles, directamente en el navegador y sin servicios externos.",
      "pitch": "Horama 3D acerca la personalización paramétrica a cualquier navegador. Reúne visor, validación STL, geometría local y exportación en una sola experiencia. Sus módulos convierten modelos, imágenes y texto en productos listos para fabricar sin enviar los archivos del usuario a otro servicio.",
      "audience": [
        "Makers",
        "Fabricación digital",
        "E-commerce"
      ],
      "features": [
        "Procesamiento local: visor, validación STL y generación de geometría en el navegador",
        "Módulos listos: lámparas, urnas, clickers, texturas, letreros y brazaletes",
        "Imagen por capas: cuantización por color y exportación multicolor en 3MF"
      ],
      "version": "1.0.0",
      "status": "stable",
      "status_label": "v1.0 pública",
      "color": "#ffc400",
      "ink": "#111111",
      "accent": "#fff3b0",
      "product_url": "https://horama-apps.github.io/Horama3D/?demo=true",
      "product_cta_label": "Ver Configurador ↓",
      "embed_url": "https://horama-apps.github.io/Horama3D/?demo=true",
      "embed_label": "CONFIGURADOR INTERACTIVO",
      "embed_title": "Diseña una pieza desde cero.",
      "embed_caption": "Prueba el generador de letreros directamente aquí. Esta demostración permite configurar y visualizar el modelo, pero mantiene la descarga deshabilitada.",
      "support_ask": "Buscamos comercios piloto, soporte de infraestructura y expertos en 3D web.",
      "roadmap": [
        {
          "title": "Motor 3D local",
          "description": "Carga, validación, órbita, autoencuadre y operaciones geométricas en el navegador",
          "state": "done"
        },
        {
          "title": "Catálogo modular",
          "description": "Lámparas, urnas con cavidad y ribs, clickers, texturas, letreros y brazaletes",
          "state": "done"
        },
        {
          "title": "Image Layers multicolor",
          "description": "Imagen cuantizada convertida en capas de color y empaquetada como 3MF",
          "state": "done"
        },
        {
          "title": "Llaveros desde imagen",
          "description": "Nuevo módulo de imagen a geometría con controles de fabricación",
          "state": "current"
        },
        {
          "title": "Configurador comercial",
          "description": "Catálogo, cotización y checkout",
          "state": "next"
        }
      ]
    },
    {
      "slug": "genai-studio",
      "name": "GenAI Studio",
      "monogram": "G",
      "logo": "/apps/genai-studio/logo.png",
      "theme": "dark",
      "tagline": "Tu estudio de contenido con IA, en cualquier pantalla.",
      "summary": "Una interfaz simple y responsiva para convertir workflows de IA en herramientas de producción accesibles desde iPhone, Android o computadora.",
      "pitch": "GenAI Studio convierte una instalación propia de ComfyUI en un estudio de producción usable por todo el equipo. Negocios, influencers y creadores pueden editar imágenes, transformar estilos, generar audio y descargar resultados sin navegar grafos técnicos. Cada workflow nuevo aparece como una herramienta clara y reutilizable, lista para trabajar desde el teléfono o la computadora.",
      "opportunity_title": "Menos nodos. Más contenido listo para publicar.",
      "opportunity_body": "Lleva tus workflows de IA a una interfaz que entiende el equipo creativo. Elige una modalidad, carga referencias, escribe la instrucción y sigue el resultado desde una cola unificada, usando tu propia infraestructura.",
      "opportunity_highlights": [
        "Diseñado para móvil",
        "Workflows reutilizables",
        "Infraestructura propia"
      ],
      "audience": [
        "Negocios y marcas",
        "Influencers",
        "Creadores de contenido"
      ],
      "features": [
        "Producción multiformato: edición y simplificación de imágenes, generación de voz y espacio preparado para video",
        "Experiencia sin complejidad técnica: formularios claros, uploads, micrófono, cola de trabajos y descarga de resultados",
        "Catálogo extensible: agrega nuevos workflows de ComfyUI sin reescribir la interfaz ni el backend"
      ],
      "version": "0.1.0",
      "status": "alpha",
      "status_label": "Alpha funcional",
      "color": "#ff6a3d",
      "ink": "#101114",
      "accent": "#ffd8cc",
      "support_ask": "Buscamos negocios, influencers y equipos de contenido para diseñar workflows repetibles, además de aliados con infraestructura de GPU y distribución creativa.",
      "roadmap": [
        {
          "title": "Estudio responsivo",
          "description": "Interfaz para iPhone, Android y computadora con jobs asíncronos y resultados descargables",
          "state": "done"
        },
        {
          "title": "Imagen y voz",
          "description": "Edición visual, simplificación de estilo y voz desde texto con audio de referencia",
          "state": "done"
        },
        {
          "title": "Flujos para contenido",
          "description": "Presets para campañas, producto, redes sociales y producción de video",
          "state": "current"
        },
        {
          "title": "Espacios de equipo",
          "description": "Biblioteca compartida, permisos e historial por marca o creador",
          "state": "next"
        }
      ]
    },
    {
      "slug": "kiroku",
      "name": "Kiroku",
      "monogram": "K",
      "logo": "/apps/kiroku/logo.svg",
      "theme": "dark",
      "tagline": "Recuerda lo que importa.",
      "summary": "Una app nativa para iPhone que transforma notas de voz en memoria personal organizada, con transcripción, resumen, etiquetas y acciones claras.",
      "pitch": "Las ideas, acuerdos y recuerdos importantes suelen aparecer cuando no hay tiempo para escribir. Kiroku permite capturarlos hablando y convierte cada grabación en una nota estructurada que puedes volver a encontrar y utilizar. La biblioteca vive en el iPhone con SwiftData, mientras un gateway privado procesa el audio con Whisper y Ollama sin exponer directamente la infraestructura. A largo plazo, Kiroku busca extender esa memoria privada con captura manos libres y recordatorios físicos opcionales.",
      "opportunity_title": "Habla ahora. Encuentra el recuerdo cuando lo necesites.",
      "opportunity_body": "Kiroku reduce la distancia entre una idea espontánea y una memoria útil. Graba desde el iPhone y recibe una nota con título, resumen, transcripción, tipo, etiquetas y próximos pasos, lista para conservar y consultar.",
      "opportunity_highlights": [
        "Nativa para iPhone",
        "Memoria local con SwiftData",
        "IA mediante gateway privado"
      ],
      "audience": [
        "Profesionales",
        "Personas con muchas ideas",
        "Equipos y reuniones"
      ],
      "features": [
        "Captura por voz: grabación nativa con pausa, reproducción y conservación opcional del audio original",
        "Notas estructuradas: Whisper transcribe y Ollama organiza título, resumen, tipo, etiquetas y acciones",
        "Privacidad por arquitectura: datos locales, API autenticada y credenciales protegidas en el Keychain de iOS"
      ],
      "version": "0.1.0",
      "status": "alpha",
      "status_label": "Alpha nativa para iPhone",
      "color": "#0171c6",
      "ink": "#0b0d10",
      "accent": "#9fd5ff",
      "support_ask": "Buscamos usuarios de iPhone que capturen ideas, reuniones y reflexiones por voz, además de aliados para probar búsqueda, procesamiento privado y futuros companions de voz e impresión térmica.",
      "roadmap": [
        {
          "title": "App nativa y memoria local",
          "description": "SwiftUI, SwiftData, grabación con AVFoundation y experiencia bilingüe en iOS 17",
          "state": "done"
        },
        {
          "title": "Voz a nota estructurada",
          "description": "Upload autenticado, Whisper, Ollama, estados de procesamiento y reintento seguro",
          "state": "done"
        },
        {
          "title": "Ask Kiroku y búsqueda",
          "description": "Consulta semántica de la memoria personal y recuperación de notas relacionadas",
          "state": "current"
        },
        {
          "title": "Memoria en el espacio físico",
          "description": "Integraciones opcionales con Seeed Studio ReSpeaker para captura manos libres y Thermal Sticky para hacer visibles recordatorios y acciones",
          "state": "next"
        }
      ]
    }
  ]
} as const;
export const siteTranslations = {
  "organization": {
    "description": "Horama Apps is an incubator and seedbed for independent applications. We build useful products, bring them to their first community, and seek sponsorships, partnerships, or funding to give them infrastructure and continuity.",
    "partnerships": [
      "Sponsorship",
      "Infrastructure",
      "Distribution",
      "Funding",
      "Technical collaboration"
    ]
  },
  "apps": {
    "framewise": {
      "tagline": "Your archive. Your judgment. Now on iPhone too.",
      "summary": "Framewise analyzes, scores, and organizes photo shoots from the desktop or its iPhone companion app connected to your local service. Horama never receives, stores, or trains on your photographs.",
      "pitch": "Your photo archive should not have to trade privacy for intelligent tools. Framewise finds the strongest frames, explains why they work, and helps improve only what needs attention. On iPhone, you can choose photos from your library, send them to your own analysis service, and review results and edited versions in a private mobile experience. Originals remain untouched, and your decisions remain yours.",
      "opportunity_title": "Editorial judgment, now on your iPhone too.",
      "opportunity_body": "Work through full shoots on your computer or select photos from your iPhone library. Framewise connects both workflows with explainable analysis, a private queue, and edits that respect subject, composition, and intent.",
      "opportunity_highlights": [
        "iPhone companion app",
        "Originals stay untouched",
        "Processing under your control"
      ],
      "audience": [
        "Photographers",
        "Mobile creators",
        "Creative studios"
      ],
      "features": [
        "Desktop and iPhone: analyze complete folders or choose photos directly from your iOS library",
        "Explainable culling: critique, scoring, duplicates, and editorial decisions in a private per-device library",
        "Complete workflow: analysis queue, faithful editing, local versions, and captions for sharing without touching the original"
      ],
      "demo_label": "DEMO / REAL WORKFLOW",
      "demo_title": "A complete desktop shoot, connected to iPhone.",
      "demo_caption": "A real Framewise walkthrough: contact sheet, explainable analysis, and an edited-version library. The companion app brings selection, progress, and results to iPhone while the analysis service remains under your control.",
      "demo_alt": "Framewise demo analyzing a photo shoot connected to its iPhone app",
      "status_label": "Desktop v1 · iPhone companion",
      "support_ask": "We are looking for photographers, mobile creators, and studios to test the desktop-to-iPhone workflow, plus distribution and local-hardware partners.",
      "roadmap": [
        {
          "title": "Privacy by architecture",
          "description": "Photos, analyses, and decisions stay on the user's computer",
          "state": "done"
        },
        {
          "title": "Explainable professional culling",
          "description": "Critique, ranking, duplicates, comparison, decisions, XMP, and recoverable cleanup",
          "state": "done"
        },
        {
          "title": "iPhone companion",
          "description": "PhotoKit selection, private libraries, analysis queue, edits, and captions from iOS",
          "state": "done"
        }
      ]
    },
    "horama-3d": {
      "tagline": "Configure, visualize, and manufacture in one place.",
      "summary": "A web configurator that turns models and images into printable 3D parts, directly in the browser and without external services.",
      "pitch": "Horama 3D brings parametric customization to any browser. It combines a viewer, STL validation, local geometry, and export in one experience. Its modules turn models, images, and text into manufacturing-ready products without sending the user's files to another service.",
      "audience": [
        "Makers",
        "Digital manufacturing",
        "E-commerce"
      ],
      "features": [
        "Local processing: viewer, STL validation, and in-browser geometry generation",
        "Ready modules: lamps, urns, clickers, textures, signs, and bracelets",
        "Image Layers: color quantization and multicolor 3MF export"
      ],
      "product_cta_label": "View Configurator ↓",
      "embed_label": "INTERACTIVE CONFIGURATOR",
      "embed_title": "Design a piece from scratch.",
      "embed_caption": "Try the sign generator directly here. This demo lets you configure and preview the model while keeping downloads disabled.",
      "status_label": "Public v1.0",
      "support_ask": "We are looking for pilot shops, infrastructure support, and web 3D experts.",
      "roadmap": [
        {
          "title": "Local 3D engine",
          "description": "In-browser loading, validation, orbiting, auto-framing, and geometry operations",
          "state": "done"
        },
        {
          "title": "Modular catalog",
          "description": "Lamps, cavity-and-rib urns, clickers, textures, signs, and bracelets",
          "state": "done"
        },
        {
          "title": "Multicolor Image Layers",
          "description": "A quantized image converted into color layers and packaged as 3MF",
          "state": "done"
        },
        {
          "title": "Image keychains",
          "description": "A new image-to-geometry module with manufacturing controls",
          "state": "current"
        },
        {
          "title": "Commercial configurator",
          "description": "Catalog, quoting, and checkout",
          "state": "next"
        }
      ]
    },
    "genai-studio": {
      "tagline": "Your AI content studio, on any screen.",
      "summary": "A simple responsive interface that turns AI workflows into production tools available from iPhone, Android, or desktop.",
      "pitch": "GenAI Studio turns a self-hosted ComfyUI installation into a production studio the whole team can use. Businesses, influencers, and creators can edit images, transform styles, generate audio, and download results without navigating technical graphs. Every new workflow becomes a clear, reusable tool ready to use from a phone or computer.",
      "opportunity_title": "Fewer nodes. More content ready to publish.",
      "opportunity_body": "Bring your AI workflows into an interface your creative team understands. Choose a format, upload references, write the instruction, and follow the result in one queue using your own infrastructure.",
      "opportunity_highlights": [
        "Mobile-first design",
        "Reusable workflows",
        "Your own infrastructure"
      ],
      "audience": [
        "Businesses and brands",
        "Influencers",
        "Content creators"
      ],
      "features": [
        "Multi-format production: image editing and simplification, voice generation, and a space ready for video",
        "No technical complexity: clear forms, uploads, microphone recording, job queue, and result downloads",
        "Extensible catalog: add new ComfyUI workflows without rewriting the interface or backend"
      ],
      "status_label": "Functional alpha",
      "support_ask": "We are looking for businesses, influencers, and content teams to design repeatable workflows, plus partners in GPU infrastructure and creative distribution.",
      "roadmap": [
        {
          "title": "Responsive studio",
          "description": "iPhone, Android, and desktop interface with asynchronous jobs and downloadable results",
          "state": "done"
        },
        {
          "title": "Image and voice",
          "description": "Visual editing, style simplification, and text-to-voice with reference audio",
          "state": "done"
        },
        {
          "title": "Content workflows",
          "description": "Presets for campaigns, products, social media, and video production",
          "state": "current"
        },
        {
          "title": "Team spaces",
          "description": "Shared library, permissions, and history for each brand or creator",
          "state": "next"
        }
      ]
    },
    "kiroku": {
      "tagline": "Remember what matters.",
      "summary": "A native iPhone app that turns voice notes into organized personal memory, with transcription, summaries, tags, and clear action items.",
      "pitch": "Important ideas, agreements, and memories often appear when there is no time to write. Kiroku captures them through speech and turns every recording into a structured note you can find and use later. The library lives on iPhone with SwiftData, while a private gateway processes audio with Whisper and Ollama without exposing the infrastructure directly. Long term, Kiroku aims to extend that private memory with optional hands-free capture and physical reminders.",
      "opportunity_title": "Speak now. Find the memory when you need it.",
      "opportunity_body": "Kiroku shortens the distance between a spontaneous thought and useful memory. Record on iPhone and receive a note with a title, summary, transcript, type, tags, and next steps, ready to keep and revisit.",
      "opportunity_highlights": [
        "Native for iPhone",
        "Local memory with SwiftData",
        "AI through a private gateway"
      ],
      "audience": [
        "Professionals",
        "People with many ideas",
        "Teams and meetings"
      ],
      "features": [
        "Voice capture: native recording with pause, playback, and optional retention of the original audio",
        "Structured notes: Whisper transcribes and Ollama organizes the title, summary, type, tags, and action items",
        "Privacy by architecture: local data, an authenticated API, and credentials protected in the iOS Keychain"
      ],
      "status_label": "Native iPhone alpha",
      "support_ask": "We are looking for iPhone users who capture ideas, meetings, and reflections by voice, plus partners to test search, private processing, and future voice and thermal-print companions.",
      "roadmap": [
        {
          "title": "Native app and local memory",
          "description": "SwiftUI, SwiftData, AVFoundation recording, and a bilingual iOS 17 experience",
          "state": "done"
        },
        {
          "title": "Voice to structured note",
          "description": "Authenticated upload, Whisper, Ollama, processing states, and safe retry",
          "state": "done"
        },
        {
          "title": "Ask Kiroku and search",
          "description": "Semantic conversation with personal memory and recovery of related notes",
          "state": "current"
        },
        {
          "title": "Memory in physical space",
          "description": "Optional Seeed Studio ReSpeaker hands-free capture and Thermal Sticky reminders and action items",
          "state": "next"
        }
      ]
    }
  }
} as const;
